### PR TITLE
feature/get temporal data for an entity id

### PR DESCRIPTION
**Pull request by PoulomiNandy**

### CODE REVIEW

**Comment by bobeal** [comment]
please remove all the intellij generated files.

**Comment by bobeal** [comment]
LGTM for the new endpoint.

**Comment by PoulomiNandy** [comment]
> "LGTM" -> looks good to "me"

**Comment by bobeal** [comment]
> > "LGTM" -> looks good to "me"

indeed

**Review by bobeal — APPROVED** [review]

**Pull request merged**
